name: pr-workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
  unit-test:
    name: unit-test-app
    runs-on: ubuntu-latest
    steps:
      - name: Unit Test app
        run: bun run test:unit
  integration-test:
    name: integration-test-app
    runs-on: ubuntu-latest
    steps:
      - name: Integration Test app
        run: bun run test:integration
